/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.cekl.proint.views;

import com.cekl.proint.models.Area;
import com.cekl.proint.models.Piece;
import com.cekl.proint.models.Selection;
import java.awt.GridLayout;
import java.util.HashMap;

/**
 *
 * @author caio
 */
public class TelaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form TelaPrincipal
     */
    HashMap<String, Piece> pieces = new HashMap<>();
    Selection preselected = new Selection();
    public TelaPrincipal() {
        pieces.put("Hamlet", new Piece("Hamlet"));
        pieces.put("Romeo e Julieta", new Piece("Romeu e Julieta"));
        pieces.put("Otelo", new Piece("Otelo"));
        initComponents();
        this.setLocationRelativeTo(null);
    }
    
        
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        FrameTelaCompra = new javax.swing.JFrame();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jFormattedTextField1 = new javax.swing.JFormattedTextField();
        jLabel5 = new javax.swing.JLabel();
        ComboTurns = new javax.swing.JComboBox<>();
        ComboPiece = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        ComboArea = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jToggleButton1 = new javax.swing.JToggleButton();
        jToggleButton2 = new javax.swing.JToggleButton();
        Assentos = new javax.swing.JFrame();
        jLabel1 = new javax.swing.JLabel();
        ButtonBuy = new javax.swing.JButton();
        ButtonPrint = new javax.swing.JButton();
        ButtonStats = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        FrameTelaCompra.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        FrameTelaCompra.setTitle("Compra");
        FrameTelaCompra.setAlwaysOnTop(true);
        FrameTelaCompra.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        FrameTelaCompra.setForeground(java.awt.Color.gray);
        FrameTelaCompra.setLocation(new java.awt.Point(0, 0));
        FrameTelaCompra.setModalExclusionType(java.awt.Dialog.ModalExclusionType.APPLICATION_EXCLUDE);
        FrameTelaCompra.setName("[381, 363]"); // NOI18N
        FrameTelaCompra.setSize(new java.awt.Dimension(425, 299));
        FrameTelaCompra.setType(java.awt.Window.Type.POPUP);

        jLabel2.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLabel2.setText("Compra do Ingresso");

        jLabel3.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel3.setText("Insira as suas infoamações para compra do ingresso");

        jLabel4.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel4.setText("CPF");

        try {
            jFormattedTextField1.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFormattedTextField1.setToolTipText("");
        jFormattedTextField1.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N

        jLabel5.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel5.setText("Peça");

        ComboTurns.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        ComboTurns.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Manhã", "Tarde", "Noite" }));
        ComboTurns.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboTurnsActionPerformed(evt);
            }
        });

        ComboPiece.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        ComboPiece.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Hamlet", "Romeo e Julieta", "Otelo" }));
        ComboPiece.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboPieceActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel6.setText("Turno");

        ComboArea.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        ComboArea.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "PlateiaA", "PlateiaB", "Frisa1", "Frisa2", "Frisa3", "Frisa4", "Frisa5", "Frisa6", "Camarote1", "Camarote2", "Camarote3", "Camarote4", "Camarote5", "BalcãoNobre" }));
        ComboArea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboAreaActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel7.setText("Área");

        jToggleButton1.setText("Escolher assento");
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });

        jToggleButton2.setText("Finalizar Compra");
        jToggleButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout FrameTelaCompraLayout = new javax.swing.GroupLayout(FrameTelaCompra.getContentPane());
        FrameTelaCompra.getContentPane().setLayout(FrameTelaCompraLayout);
        FrameTelaCompraLayout.setHorizontalGroup(
            FrameTelaCompraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FrameTelaCompraLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(FrameTelaCompraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(FrameTelaCompraLayout.createSequentialGroup()
                        .addComponent(jToggleButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(FrameTelaCompraLayout.createSequentialGroup()
                        .addGroup(FrameTelaCompraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addGroup(FrameTelaCompraLayout.createSequentialGroup()
                                .addGroup(FrameTelaCompraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel4))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(FrameTelaCompraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jFormattedTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ComboPiece, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ComboTurns, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(FrameTelaCompraLayout.createSequentialGroup()
                                        .addComponent(ComboArea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 75, Short.MAX_VALUE)
                                        .addComponent(jToggleButton1)))))
                        .addGap(35, 35, 35))))
        );
        FrameTelaCompraLayout.setVerticalGroup(
            FrameTelaCompraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FrameTelaCompraLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addGroup(FrameTelaCompraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jFormattedTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(FrameTelaCompraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ComboPiece, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(FrameTelaCompraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ComboTurns, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(FrameTelaCompraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ComboArea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(jToggleButton1))
                .addGap(18, 18, 18)
                .addComponent(jToggleButton2)
                .addContainerGap(31, Short.MAX_VALUE))
        );

        FrameTelaCompra.getAccessibleContext().setAccessibleDescription("");

        Assentos.setSize(new java.awt.Dimension(700, 500));

        javax.swing.GroupLayout AssentosLayout = new javax.swing.GroupLayout(Assentos.getContentPane());
        Assentos.getContentPane().setLayout(AssentosLayout);
        AssentosLayout.setHorizontalGroup(
            AssentosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        AssentosLayout.setVerticalGroup(
            AssentosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 448, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(0, 0));

        jLabel1.setText("Bem vindo ao teatro CEKL");

        ButtonBuy.setText("Comprar Ingresso");
        ButtonBuy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonBuyActionPerformed(evt);
            }
        });

        ButtonPrint.setText("Imprimir ingresso");

        ButtonStats.setText("Estatística de vendas");

        jButton4.setText("Sair");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(86, 86, 86))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(ButtonStats, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ButtonPrint, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ButtonBuy, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 345, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(ButtonBuy)
                .addGap(18, 18, Short.MAX_VALUE)
                .addComponent(ButtonPrint)
                .addGap(18, 18, Short.MAX_VALUE)
                .addComponent(ButtonStats)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 139, Short.MAX_VALUE)
                .addComponent(jButton4)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ButtonBuyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonBuyActionPerformed
        FrameTelaCompra.setLocationRelativeTo(this);
        FrameTelaCompra.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_ButtonBuyActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jToggleButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton2ActionPerformed
        FrameTelaCompra.dispose();
        this.setVisible(true);
    }//GEN-LAST:event_jToggleButton2ActionPerformed

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
        Area e = preselected.getSessao().getSeats().getAreas().get(preselected.getArea());
        GridLayout assentosLayout = new GridLayout(10, 10);
        ButtonExit = new javax.swing.JButton();
        Assentos.setLayout(assentosLayout);
        ButtonExit.setFont(new java.awt.Font("Dialog", 0, 8)); // NOI18N
        ButtonExit.setText("X");
        ButtonExit.addActionListener((java.awt.event.ActionEvent evt1) -> {
            Assentos.getContentPane().removeAll();
            Assentos.setVisible(false);
        });
        Assentos.add(ButtonExit);
        for (int i = 0; i < e.getTotalSeats(); i++) {
            Assentos.add(new SeatButton("botao"+i, Integer.toString(i), e.isSeatOccupied(i), preselected, Assentos));
        }
        Assentos.setVisible(true);
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    private void ComboAreaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboAreaActionPerformed
        preselected.setArea(ComboArea.getSelectedIndex());
        System.out.println(preselected.getArea());
    }//GEN-LAST:event_ComboAreaActionPerformed

    private void ComboPieceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboPieceActionPerformed
        preselected.setPeca(pieces.get(ComboPiece.getSelectedItem().toString()));
        System.out.println(preselected.getPeca());
    }//GEN-LAST:event_ComboPieceActionPerformed

    private void ComboTurnsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboTurnsActionPerformed
        preselected.setSessao(preselected.getPeca().getTurns().get(ComboTurns.getSelectedItem().toString()));
        System.out.println(preselected.getSessao());
    }//GEN-LAST:event_ComboTurnsActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }
    private javax.swing.JButton ButtonExit;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFrame Assentos;
    private javax.swing.JButton ButtonBuy;
    private javax.swing.JButton ButtonPrint;
    private javax.swing.JButton ButtonStats;
    private javax.swing.JComboBox<String> ComboArea;
    private javax.swing.JComboBox<String> ComboPiece;
    private javax.swing.JComboBox<String> ComboTurns;
    private javax.swing.JFrame FrameTelaCompra;
    private javax.swing.JButton jButton4;
    private javax.swing.JFormattedTextField jFormattedTextField1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JToggleButton jToggleButton2;
    // End of variables declaration//GEN-END:variables
}
